### ISSUE TITLE
Stop the app stealing focus away from the game

### ISSUE THREAD

**Issue by MFAshby** [MFAshby/GuildWarsItemBrowser#6]
It's annoying having to click back on the game. Make it lose focus once you stop hovering over it.

**Comment by CheshireSwift** [comment]
To the best of my knowledge, either we can call blur() and Overwolf will notice nothing has focus, or there's no way for us to give focus back to the game programmatically.

**Comment by CheshireSwift** [comment]
Moving the mouse out of the Overwolf window doesn't appear to trigger jQuery's mouseleave events (thanks to a quirk of positioning, you actually get the mouseleave when you mouseover, afaict). I'm not sure this is actually possible. Have we got any examples of other apps that do it?

**Comment by MFAshby** [comment]
nope, maybe try a few and see if the bug is universal.. then maybe get on the OW developer forum.

**Comment by CheshireSwift** [comment]
I'm not sure it constitutes a bug? It seems just a function of normal window focus behaviour? It is a separate application after all.

**Comment by MFAshby** [comment]
I would guess so. Also I can't think of any way of transferring focus off the whole window in JS. Also nothing about it in overwolf API.
